### ISSUE TITLE
db:migrate error

### ISSUE THREAD

**Issue by mgarciaarag** [AjuntamentDeTerrassa/decidim-terrassa#65]
# This is a Bug Report

#### :tophat: Description

For bug reports:
* What went wrong?
I'm trying to install a local copy of Decidim Terrassa from the current repo, but after doing a db:create I tried to make an db:migrate. After doing some db statements, I get the error:

```
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant Decidim::Results
/home/manu/Documentos/RubyApps/decidim-terrassa-master/db/migrate/20170320140546_add_reference_to_results.decidim_results.rb:5:in `change'
```

* What did you expect should have happened?
I expected to get a db up to test decidim Terrassa

* What was the config you used?
```
$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

$ cat database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  
development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "decidim_terrassa_development" } %>

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  #username: decidim_terrassa

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "decidim_terrassa_test" } %>

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  url: <%= ENV['DATABASE_URL'] %>
```

* What stacktrace or error message from your provider did you see?
```
== 20170320140545 RemoveShortDescriptionFromResults: migrated (0.0015s) =======

== 20170320140546 AddReferenceToResults: migrating ============================
-- add_column(:decidim_results_results, :reference, :string)
   -> 0.0008s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant Decidim::Results
/home/manu/Documentos/RubyApps/decidim-terrassa-master/db/migrate/20170320140546_add_reference_to_results.decidim_results.rb:5:in `change'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:792:in `exec_migration'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:775:in `block in migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:774:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:953:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `ddl_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `each'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1148:in `block in migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1148:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1007:in `up'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:985:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/manu/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/manu/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/manu/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/home/manu/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
/home/manu/Documentos/RubyApps/decidim-terrassa-master/bin/rails:9:in `require'
/home/manu/Documentos/RubyApps/decidim-terrassa-master/bin/rails:9:in `<top (required)>'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/manu/Documentos/RubyApps/decidim-terrassa-master/bin/spring:15:in `require'
/home/manu/Documentos/RubyApps/decidim-terrassa-master/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
NameError: uninitialized constant Decidim::Results
/home/manu/Documentos/RubyApps/decidim-terrassa-master/db/migrate/20170320140546_add_reference_to_results.decidim_results.rb:5:in `change'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:792:in `exec_migration'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:775:in `block in migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:774:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:953:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1298:in `ddl_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `each'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1148:in `block in migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1148:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1007:in `up'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:985:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/home/manu/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/manu/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/manu/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/manu/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/home/manu/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
/home/manu/Documentos/RubyApps/decidim-terrassa-master/bin/rails:9:in `require'
/home/manu/Documentos/RubyApps/decidim-terrassa-master/bin/rails:9:in `<top (required)>'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/manu/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/manu/Documentos/RubyApps/decidim-terrassa-master/bin/spring:15:in `require'
/home/manu/Documentos/RubyApps/decidim-terrassa-master/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by mrcasals** [comment]
I'm not sure about how to proceed here. `Decidim::Results` come from an older gem that Decidim Terrassa no longer uses, so you can remove these failing migrations meanwhile @mgarciaarag.

I guess we should delete the migrations from the repo. /cc @oriolgual @josepjaume
